title: doITbest-ngo
description: doITbest NGO website
url: "https://doITbest-ngo.github.io"
baseurl: ""

theme: jekyll-theme-architect

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
